[focusX,focusY] = meshgrid(linspace(10,100,10));
loopi = 8;
loopj = 2;
x = focusX(loopi,loopj);
y = focusY(loopi,loopj);
filename = strcat('x',num2str(x),'y',num2str(y));
%filename = 'flat';
foldername = strcat('result1/',filename);
smapname = strcat(foldername,'/smap.dat');
fmapname = strcat(foldername,'/fmap.dat');
tmapsname = strcat(foldername,'/tmaps.dat');
tmapfname = strcat(foldername,'/tmapf.dat');
fmap = dlmread(fmapname);
smap = dlmread(smapname);
tmaps = dlmread(tmapsname);
tmapf = dlmread(tmapfname);
subplot(2,2,1);
imagesc(fmap);
axis image;
colorbar;
title('Fundamental Intensity','FontSize',16);
subplot(2,2,2);
imagesc(smap);
axis image;
colorbar;
title('SHG Intensity','FontSize',16);
subplot(2,2,3);
imagesc(tmapf);
axis image;
colorbar;
title('Fundamental Pulse Duration','FontSize',16);
subplot(2,2,4);
imagesc(tmaps);
axis image;
colorbar;
title('SHG Pulse Duration','FontSize',16);

